import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=process.argv[2] ? path.resolve(process.argv[2]) : path.join(root,'releases','B-Zone-Offline-Mac-AppleSilicon-2026-10-01');
if(fs.existsSync(output)) throw Error(`Output already exists: ${output}`);
const modules=process.env.NFC_MODULE_ROOT || '/Users/chunming/F/F-table/server';
const copy=(from,to)=>fs.cpSync(from,to,{recursive:true,verbatimSymlinks:true});
fs.mkdirSync(output,{recursive:true});
for(const file of ['launcher.cjs','static.cjs','Start.command','Stop.command','Pair.command','README.txt']) copy(path.join(root,'offline',file),path.join(output,file));
copy(path.join(root,'dist'),path.join(output,'tv'));
copy(path.join(root,'B-Table/dist'),path.join(output,'table'));
copy(path.join(root,'server'),path.join(output,'server'));
copy(path.join(modules,'node_modules'),path.join(output,'server/node_modules'));
copy(path.join(root,'B-Table/server/uid-map.json'),path.join(output,'B-Table/server/uid-map.json'));
copy(path.join(root,'B2.0-design.json'),path.join(output,'B2.0-design.json'));
fs.mkdirSync(path.join(output,'runtime'),{recursive:true});
copy(process.execPath,path.join(output,'runtime/node'));
copy(path.resolve(process.execPath,'../../LICENSE'),path.join(output,'runtime/LICENSE'));
fs.mkdirSync(path.join(output,'browser'),{recursive:true});
console.log('Copying bundled Chrome…');
execFileSync('/usr/bin/ditto',['/Applications/Google Chrome.app',path.join(output,'browser/Google Chrome.app')]);
for(const file of ['Start.command','Stop.command','Pair.command','runtime/node'])fs.chmodSync(path.join(output,file),0o755);
fs.writeFileSync(path.join(output,'build-info.json'),JSON.stringify({created:new Date().toISOString(),platform:process.platform,arch:process.arch,node:process.version,minMacOS:'13.5',tableCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:path.join(root,'B-Table'),encoding:'utf8'}).trim(),ports:{table:5273,tv:5284,nfc:8788}},null,2));
console.log(output);
